Connected to Python 3.12.3

In [ ]:
# Code to search for interactions (hydrogen bonds) present in simulations;
# Specifically around ASP_25 (chain A) or ASP_124 (chain B), plus nearby residues
# Goal: see the differences in interactions of two conditions Monoprotonated (MP) and Unprotoated (DP) 


#IMPORTS
import os
import pandas as pd

#SETUP
rootdir = '/home/sdv/m1isdd/aperova/Documents/M1_STAGE/Data/interactions/'
os.chdir(rootdir)

#FUNCTIONS
# a. Open interactions file
def find_asp_int(interactions_file):
    interactions_df = pd.read_csv(interactions_file)
    HB_ASP_25_cols = [col for col in interactions_df.columns if 'ASP_25' in col and 'hb' in col]
    for present_interactions in HB_ASP_25_cols:
        if interactions_df[present_interactions].sum() > 0:
            print(present_interactions)

# b. Analyse Asp_bonds
def analyze_asp_hbonds(interactions_file):
    df = pd.read_csv(interactions_file)
    n_frames = len(df)
    resid_list = ['23','24','25','26','27','28','123','124','125','126','128']
    # Filter columns for H-bonds involving Asp 25/124 and near residues
    hb_cols = [col for col in df.columns if 'hb' in col and any(resid in col for resid in resid_list)]
        
    results = []
    for col in hb_cols:
        # Calculate frequency: % of frames where the bond exists (val > 0)
        frequency = (df[col] > 0).sum() / n_frames * 100
        if frequency > 5.0: # Only care about bonds present > 1% of time
            results.append({'Interaction': col, 'Frequency': frequency})
    
    # Return as a DataFrame sorted by importance
    return pd.DataFrame(results).sort_values(by='Frequency', ascending=False)




#MAIN

# Run for different files to compare

#print("\nV11 (Unstable UP) H-bonds:")
#print(analyze_asp_hbonds('res_V11.csv'))

#print("\nV8 (Stable MP) H-bonds:")
#print(analyze_asp_hbonds('res_V8.csv'))

#print("\nV7 (Stable MP) H-bonds:")
#print(analyze_asp_hbonds('res_V7.csv'))

#print("V12 (Stable UP) H-bonds:")
#print(analyze_asp_hbonds('res_V12.csv'))

#print("\nV21 (Stable MP) H-bonds:")
#print(analyze_asp_hbonds('res_V21.csv'))

#print("\nV1 (Stable MP) H-bonds:")
#analyze_asp_hbonds('res_V1.csv')



# Or make it automatic

# 1. fetch all interaction files
#store all file paths
simulations_list = ['res_V1.csv', 'res_V11.csv', 'res_V12.csv', 'res_V21.csv', 'res_V7.csv', 'res_V8.csv']
interactions_files_paths = []

# 2. iterate on each file
for root, dirs, files in os.walk(rootdir):
    for name in files:
        if name in simulations_list:
            interactions_files_paths.append(os.path.join(rootdir, name))

# 3. use function and print the result
for i, interactions_file in enumerate(interactions_files_paths):
    # get simulation name from filename
    simulation_name = os.path.basename(os.path.normpath(interactions_file)).replace("res_", "").replace(".csv", "")
    print(f"Simulation: {simulation_name}")
    analyze_asp_hbonds(interactions_file)

Simulation: V7
Simulation: V1
Simulation: V21
Simulation: V11
Simulation: V12
Simulation: V8

In [ ]:
pd.read_csv('res_V11.csv')

,vdw_ALA_172_C_VAL_161_O,vdw_GLY_49_CA_MET_76_CE,vdw_GLY_52_O_ILE_149_N,vdw_ILE_114_CA_ILE_163_CD,vdw_GLY_185_C_LEU_189_CD1,vdw_ARG_186_CB_THR_190_CG2,vdw_ILE_181_CB_THR_179_CG2,vdw_GLY_17_C_TYR_14_CA,vdw_ILE_32_CG2_ILE_82_CB,vdw_ARG_186_CB_TRP_6_NE1,...,hbsb_ALA_133_N_ASN_182_OD1,vdw_ALA_127_C_ARG_186_CG,hbsb_PRO_1_O_SER_4_OG,vdw_ILE_149_O_PRO_180_CB,vdw_GLN_117_CD_GLY_134_O,vdw_LEU_5_CB_PHE_3_CD1,vdw_GLU_162_CD_GLU_164_OE1,vdw_GLY_51_C_PHE_152_C,vdw_ASN_98_CG_PRO_1_O,hbsb_GLN_2_NE2_SER_4_N
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
997,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
998,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
999,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1000,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
interactions_v11 = pd.read_csv('res_V11.csv')

In [ ]:
interactions_v12 = pd.read_csv('res_V12.csv')

In [ ]:
interactions_v1 = pd.read_csv('res_V1.csv')

In [ ]:
interactions_v7 = pd.read_csv('res_V7.csv')

In [ ]:
interactions_v8 = pd.read_csv('res_V8.csv')

In [ ]:
interactions_v21 = pd.read_csv('res_V21.csv')

In [ ]:
interactions_db = [interactions_v]

NameError: name 'interactions_v' is not defined

In [ ]:
interactions_db = [interactions_v1, interactions_v11, interactions_v12, interactions_v7, interactions_v8, interactions_v21]

In [ ]:
for int_file in interactions_db:    print int_file.shape()

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (<ipython-input-11-ccced28b1331>, line 1)

In [ ]:
for int_file in interactions_db:    print(int_file.shape())

TypeError: 'tuple' object is not callable

In [ ]:
for int_file in interactions_db:    print(int_file.shape)

(1001, 21391)
(1001, 21391)
(1001, 21391)
(1001, 21391)
(501, 21391)
(501, 21391)

In [ ]:
select_df = pd.DataFrame(columns=['interactions_v1', 'interactions_v11', 'interactions_v12', 'interactions_v7', 'interactions_v8', 'interactions_v21']) for int_file in interactions_db:    select_col = int_file['hbsb_THR_125_O_THR_26_OG1'] select_df[int_file] = select_col

SyntaxError: invalid syntax (<ipython-input-14-85b91a8e0e93>, line 1)

In [ ]:
select_df = pd.DataFrame(columns=['interactions_v1', 'interactions_v11', 'interactions_v12', 'interactions_v7', 'interactions_v8', 'interactions_v21'])
for int_file in interactions_db:
    select_col = int_file['hbsb_THR_125_O_THR_26_OG1']
    select_df[int_file] = select_col

TypeError: Must pass DataFrame or 2-d ndarray with boolean values only

In [ ]:
pd.conc

AttributeError: module 'pandas' has no attribute 'conc'

In [ ]:
pd.concat(interactions_db)

,vdw_ALA_172_C_VAL_161_O,vdw_GLY_49_CA_MET_76_CE,vdw_GLY_52_O_ILE_149_N,vdw_ILE_114_CA_ILE_163_CD,vdw_GLY_185_C_LEU_189_CD1,vdw_ARG_186_CB_THR_190_CG2,vdw_ILE_181_CB_THR_179_CG2,vdw_GLY_17_C_TYR_14_CA,vdw_ILE_32_CG2_ILE_82_CB,vdw_ARG_186_CB_TRP_6_NE1,...,hbsb_ALA_133_N_ASN_182_OD1,vdw_ALA_127_C_ARG_186_CG,hbsb_PRO_1_O_SER_4_OG,vdw_ILE_149_O_PRO_180_CB,vdw_GLN_117_CD_GLY_134_O,vdw_LEU_5_CB_PHE_3_CD1,vdw_GLU_162_CD_GLU_164_OE1,vdw_GLY_51_C_PHE_152_C,vdw_ASN_98_CG_PRO_1_O,hbsb_GLN_2_NE2_SER_4_N
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
497,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
498,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
499,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
500,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
concat_df = pd.concat(interactions_db)

In [ ]:
concat_df['simulation'] = []    concat_df.loc[[0:1001], 'simulation'] = 'V1'    concat_df.loc[[1001:2002], 'simulation'] = 'V11'   concat_df.loc[[2002:3003], 'simulation'] = 'V12'    concat_df.loc[[3003:4004], 'simulation'] = 'V7'    concat_df.loc[[4004:4505], 'simulation'] = 'V8'    concat_df.loc[[4505:5006], 'simulation'] = 'V21'   concat_df.set_index("simulation")

SyntaxError: invalid syntax (<ipython-input-19-2ec3b3b1f201>, line 1)

In [ ]:
concat_df['simulation'] = []
concat_df.loc[[0,1001], 'simulation'] = 'V1'
concat_df.loc[[1001,2002], 'simulation'] = 'V11'
concat_df.loc[[2002,3003], 'simulation'] = 'V12'
concat_df.loc[[3003,4004], 'simulation'] = 'V7'
concat_df.loc[[4004,4505], 'simulation'] = 'V8'
concat_df.loc[[4505,5006], 'simulation'] = 'V21'
concat_df.set_index("simulation")

ValueError: Length of values (0) does not match length of index (5006)

In [ ]:
concat_df['simulation'] = ""
concat_df.loc[[0,1001], 'simulation'] = 'V1'
concat_df.loc[[1001,2002], 'simulation'] = 'V11'
concat_df.loc[[2002,3003], 'simulation'] = 'V12'
concat_df.loc[[3003,4004], 'simulation'] = 'V7'
concat_df.loc[[4004,4505], 'simulation'] = 'V8'
concat_df.loc[[4505,5006], 'simulation'] = 'V21'
concat_df.set_index("simulation")

KeyError: '[1001] not in index'

In [ ]:
concat_df['simulation'] = ""
concat_df.iloc[[0:1001], 'simulation'] = 'V1'
concat_df.iloc[[1001:2002], 'simulation'] = 'V11'
concat_df.iloc[[2002:3003], 'simulation'] = 'V12'
concat_df.iloc[[3003:4004], 'simulation'] = 'V7'
concat_df.iloc[[4004:4505], 'simulation'] = 'V8'
concat_df.iloc[[4505:5006], 'simulation'] = 'V21'
concat_df.set_index("simulation")

SyntaxError: invalid syntax (<ipython-input-22-c486d3838bb5>, line 2)

In [ ]:
concat_df['simulation'] = ""
concat_df.iloc[0:1001, 'simulation'] = 'V1'
concat_df.iloc[1001:2002, 'simulation'] = 'V11'
concat_df.iloc[2002:3003, 'simulation'] = 'V12'
concat_df.iloc[3003:4004, 'simulation'] = 'V7'
concat_df.iloc[4004:4505, 'simulation'] = 'V8'
concat_df.iloc[4505:5006, 'simulation'] = 'V21'
concat_df.set_index("simulation")

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
concat_df

,vdw_ALA_172_C_VAL_161_O,vdw_GLY_49_CA_MET_76_CE,vdw_GLY_52_O_ILE_149_N,vdw_ILE_114_CA_ILE_163_CD,vdw_GLY_185_C_LEU_189_CD1,vdw_ARG_186_CB_THR_190_CG2,vdw_ILE_181_CB_THR_179_CG2,vdw_GLY_17_C_TYR_14_CA,vdw_ILE_32_CG2_ILE_82_CB,vdw_ARG_186_CB_TRP_6_NE1,...,vdw_ALA_127_C_ARG_186_CG,hbsb_PRO_1_O_SER_4_OG,vdw_ILE_149_O_PRO_180_CB,vdw_GLN_117_CD_GLY_134_O,vdw_LEU_5_CB_PHE_3_CD1,vdw_GLU_162_CD_GLU_164_OE1,vdw_GLY_51_C_PHE_152_C,vdw_ASN_98_CG_PRO_1_O,hbsb_GLN_2_NE2_SER_4_N,simulation
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,
497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,
498,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,
499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,
500,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,

In [ ]:
concat_df.iloc[0:1001, 'simulation'] = 'V1'

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
concat_df.iloc[0:1001] = 'V1'

<ipython-input-26-00a84749e9bb>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'V1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  concat_df.iloc[0:1001] = 'V1'

In [ ]:
concat_df.iloc[0:1001]

,vdw_ALA_172_C_VAL_161_O,vdw_GLY_49_CA_MET_76_CE,vdw_GLY_52_O_ILE_149_N,vdw_ILE_114_CA_ILE_163_CD,vdw_GLY_185_C_LEU_189_CD1,vdw_ARG_186_CB_THR_190_CG2,vdw_ILE_181_CB_THR_179_CG2,vdw_GLY_17_C_TYR_14_CA,vdw_ILE_32_CG2_ILE_82_CB,vdw_ARG_186_CB_TRP_6_NE1,...,vdw_ALA_127_C_ARG_186_CG,hbsb_PRO_1_O_SER_4_OG,vdw_ILE_149_O_PRO_180_CB,vdw_GLN_117_CD_GLY_134_O,vdw_LEU_5_CB_PHE_3_CD1,vdw_GLU_162_CD_GLU_164_OE1,vdw_GLY_51_C_PHE_152_C,vdw_ASN_98_CG_PRO_1_O,hbsb_GLN_2_NE2_SER_4_N,simulation
0,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1,...,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1
1,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1,...,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1
2,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1,...,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1
3,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1,...,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1
4,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1,...,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1,...,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1
997,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1,...,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1
998,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1,...,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1
999,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1,...,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1
1000,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1,...,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1

In [ ]:
interactions_v1 = pd.read_csv('res_V1.csv')

In [ ]:
interactions_v11 = pd.read_csv('res_V11.csv')

In [ ]:
interactions_v12 = pd.read_csv('res_V12.csv')

In [ ]:
interactions_v7 = pd.read_csv('res_V7.csv')

In [ ]:
interactions_v8 = pd.read_csv('res_V8.csv')

In [ ]:
interactions_v21 = pd.read_csv('res_V21.csv')

In [ ]:
interactions_db = [interactions_v1, interactions_v11, interactions_v12, interactions_v7, interactions_v8, interactions_v21]

In [ ]:
concat_df = pd.concat(interactions_db)

In [ ]:
concat_df.loc[0:1001, 'simulation'] = 'V1'

KeyError: 'Cannot get left slice bound for non-unique label: 0'

In [ ]:
co

NameError: name 'co' is not defined

In [ ]:
concat_df['simulation'] = ''

In [ ]:
conc

NameError: name 'conc' is not defined

In [ ]:
concat_df.set_index('simulation')

,vdw_ALA_172_C_VAL_161_O,vdw_GLY_49_CA_MET_76_CE,vdw_GLY_52_O_ILE_149_N,vdw_ILE_114_CA_ILE_163_CD,vdw_GLY_185_C_LEU_189_CD1,vdw_ARG_186_CB_THR_190_CG2,vdw_ILE_181_CB_THR_179_CG2,vdw_GLY_17_C_TYR_14_CA,vdw_ILE_32_CG2_ILE_82_CB,vdw_ARG_186_CB_TRP_6_NE1,...,hbsb_ALA_133_N_ASN_182_OD1,vdw_ALA_127_C_ARG_186_CG,hbsb_PRO_1_O_SER_4_OG,vdw_ILE_149_O_PRO_180_CB,vdw_GLN_117_CD_GLY_134_O,vdw_LEU_5_CB_PHE_3_CD1,vdw_GLU_162_CD_GLU_164_OE1,vdw_GLY_51_C_PHE_152_C,vdw_ASN_98_CG_PRO_1_O,hbsb_GLN_2_NE2_SER_4_N
simulation,,,,,,,,,,,,,,,,,,,,,
,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
concat_df.iloc[0:1001, 'simulation'] = 'V1'

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
concat_df.loc[0:1001, 'simulation'] = 'V1'

KeyError: 'Cannot get left slice bound for non-unique label: 0'

In [ ]:

r1 =0
r2 = 5006
li = list(range(r1, r2))
concat_df['simulation'] = li
concat_df.set_index("simulation")
concat_df.loc[0:1001, 'simulation'] = 'V1'
concat_df.loc[1001:2002, 'simulation'] = 'V11'
concat_df.loc[2002:3003, 'simulation'] = 'V12'
concat_df.loc[3003:4004, 'simulation'] = 'V7'
concat_df.loc[4004:4505, 'simulation'] = 'V8'
concat_df.loc[4505:5006, 'simulation'] = 'V21'

KeyError: 'Cannot get left slice bound for non-unique label: 0'

In [ ]:
concat

NameError: name 'concat' is not defined

In [ ]:
concat_df

,vdw_ALA_172_C_VAL_161_O,vdw_GLY_49_CA_MET_76_CE,vdw_GLY_52_O_ILE_149_N,vdw_ILE_114_CA_ILE_163_CD,vdw_GLY_185_C_LEU_189_CD1,vdw_ARG_186_CB_THR_190_CG2,vdw_ILE_181_CB_THR_179_CG2,vdw_GLY_17_C_TYR_14_CA,vdw_ILE_32_CG2_ILE_82_CB,vdw_ARG_186_CB_TRP_6_NE1,...,vdw_ALA_127_C_ARG_186_CG,hbsb_PRO_1_O_SER_4_OG,vdw_ILE_149_O_PRO_180_CB,vdw_GLN_117_CD_GLY_134_O,vdw_LEU_5_CB_PHE_3_CD1,vdw_GLU_162_CD_GLU_164_OE1,vdw_GLY_51_C_PHE_152_C,vdw_ASN_98_CG_PRO_1_O,hbsb_GLN_2_NE2_SER_4_N,simulation
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5001
497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5002
498,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5003
499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5004
500,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5005

In [ ]:
concat_df.set_index('simulation')

,vdw_ALA_172_C_VAL_161_O,vdw_GLY_49_CA_MET_76_CE,vdw_GLY_52_O_ILE_149_N,vdw_ILE_114_CA_ILE_163_CD,vdw_GLY_185_C_LEU_189_CD1,vdw_ARG_186_CB_THR_190_CG2,vdw_ILE_181_CB_THR_179_CG2,vdw_GLY_17_C_TYR_14_CA,vdw_ILE_32_CG2_ILE_82_CB,vdw_ARG_186_CB_TRP_6_NE1,...,hbsb_ALA_133_N_ASN_182_OD1,vdw_ALA_127_C_ARG_186_CG,hbsb_PRO_1_O_SER_4_OG,vdw_ILE_149_O_PRO_180_CB,vdw_GLN_117_CD_GLY_134_O,vdw_LEU_5_CB_PHE_3_CD1,vdw_GLU_162_CD_GLU_164_OE1,vdw_GLY_51_C_PHE_152_C,vdw_ASN_98_CG_PRO_1_O,hbsb_GLN_2_NE2_SER_4_N
simulation,,,,,,,,,,,,,,,,,,,,,
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5001,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
5002,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
5003,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
5004,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
5005,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
concat_df.loc[0:1001, 'simulation'] = 'V1'
concat_df.loc[1001:2002, 'simulation'] = 'V11'
concat_df.loc[2002:3003, 'simulation'] = 'V12'
concat_df.loc[3003:4004, 'simulation'] = 'V7'
concat_df.loc[4004:4505, 'simulation'] = 'V8'
concat_df.loc[4505:5006, 'simulation'] = 'V21'

KeyError: 'Cannot get left slice bound for non-unique label: 0'

In [ ]:
concat_df.loc[0:1001]['simulation'] = 'V1'
concat_df

KeyError: 'Cannot get left slice bound for non-unique label: 0'

In [ ]:
concat_df.loc['simulation'][0:1001] = 'V1'
concat_df

KeyError: 'simulation'

In [ ]:
concat_df.loc[concat_df['simulation'] >= 0 and < 1001] = 'V1'
concat_df

SyntaxError: invalid syntax (<ipython-input-50-e982f74eb4e0>, line 1)

In [ ]:
concat_df.loc[concat_df['simulation'] >= 0 and < 1001, 0:1] = 'V1'


concat_df

SyntaxError: invalid syntax (<ipython-input-51-a90801a5e1d3>, line 1)

In [ ]:
concat_df.loc[concat_df['simulation'] >= 0 and < 1001, 0:1]

SyntaxError: invalid syntax (<ipython-input-52-14c828796edc>, line 1)

In [ ]:
concat_df.loc[concat_df['simulation'] >= 0 and < 1001]

SyntaxError: invalid syntax (<ipython-input-53-8b536e1760ad>, line 1)

In [ ]:
concat_df.loc[concat_df['simulation']]

KeyError: '[1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373, 1374, 1375, 1376, 1377, 1378, 1379, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1408, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425, 1426, 1427, 1428, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1559, 1560, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576, 1577, 1578, 1579, 1580, 1581, 1582, 1583, 1584, 1585, 1586, 1587, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1623, 1624, 1625, 1626, 1627, 1628, 1629, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1655, 1656, 1657, 1658, 1659, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, 1774, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2072, 2073, 2074, 2075, 2076, 2077, 2078, 2079, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091, 2092, 2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111, 2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2120, 2121, 2122, 2123, 2124, 2125, 2126, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2136, 2137, 2138, 2139, 2140, 2141, 2142, 2143, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 2168, 2169, 2170, 2171, 2172, 2173, 2174, 2175, 2176, 2177, 2178, 2179, 2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2205, 2206, 2207, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2234, 2235, 2236, 2237, 2238, 2239, 2240, 2241, 2242, 2243, 2244, 2245, 2246, 2247, 2248, 2249, 2250, 2251, 2252, 2253, 2254, 2255, 2256, 2257, 2258, 2259, 2260, 2261, 2262, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2272, 2273, 2274, 2275, 2276, 2277, 2278, 2279, 2280, 2281, 2282, 2283, 2284, 2285, 2286, 2287, 2288, 2289, 2290, 2291, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2300, 2301, 2302, 2303, 2304, 2305, 2306, 2307, 2308, 2309, 2310, 2311, 2312, 2313, 2314, 2315, 2316, 2317, 2318, 2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 2330, 2331, 2332, 2333, 2334, 2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 2349, 2350, 2351, 2352, 2353, 2354, 2355, 2356, 2357, 2358, 2359, 2360, 2361, 2362, 2363, 2364, 2365, 2366, 2367, 2368, 2369, 2370, 2371, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 2398, 2399, 2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421, 2422, 2423, 2424, 2425, 2426, 2427, 2428, 2429, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2437, 2438, 2439, 2440, 2441, 2442, 2443, 2444, 2445, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 2463, 2464, 2465, 2466, 2467, 2468, 2469, 2470, 2471, 2472, 2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2481, 2482, 2483, 2484, 2485, 2486, 2487, 2488, 2489, 2490, 2491, 2492, 2493, 2494, 2495, 2496, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2509, 2510, 2511, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 2523, 2524, 2525, 2526, 2527, 2528, 2529, 2530, 2531, 2532, 2533, 2534, 2535, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2543, 2544, 2545, 2546, 2547, 2548, 2549, 2550, 2551, 2552, 2553, 2554, 2555, 2556, 2557, 2558, 2559, 2560, 2561, 2562, 2563, 2564, 2565, 2566, 2567, 2568, 2569, 2570, 2571, 2572, 2573, 2574, 2575, 2576, 2577, 2578, 2579, 2580, 2581, 2582, 2583, 2584, 2585, 2586, 2587, 2588, 2589, 2590, 2591, 2592, 2593, 2594, 2595, 2596, 2597, 2598, 2599, 2600, 2601, 2602, 2603, 2604, 2605, 2606, 2607, 2608, 2609, 2610, 2611, 2612, 2613, 2614, 2615, 2616, 2617, 2618, 2619, 2620, 2621, 2622, 2623, 2624, 2625, 2626, 2627, 2628, 2629, 2630, 2631, 2632, 2633, 2634, 2635, 2636, 2637, 2638, 2639, 2640, 2641, 2642, 2643, 2644, 2645, 2646, 2647, 2648, 2649, 2650, 2651, 2652, 2653, 2654, 2655, 2656, 2657, 2658, 2659, 2660, 2661, 2662, 2663, 2664, 2665, 2666, 2667, 2668, 2669, 2670, 2671, 2672, 2673, 2674, 2675, 2676, 2677, 2678, 2679, 2680, 2681, 2682, 2683, 2684, 2685, 2686, 2687, 2688, 2689, 2690, 2691, 2692, 2693, 2694, 2695, 2696, 2697, 2698, 2699, 2700, 2701, 2702, 2703, 2704, 2705, 2706, 2707, 2708, 2709, 2710, 2711, 2712, 2713, 2714, 2715, 2716, 2717, 2718, 2719, 2720, 2721, 2722, 2723, 2724, 2725, 2726, 2727, 2728, 2729, 2730, 2731, 2732, 2733, 2734, 2735, 2736, 2737, 2738, 2739, 2740, 2741, 2742, 2743, 2744, 2745, 2746, 2747, 2748, 2749, 2750, 2751, 2752, 2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 2762, 2763, 2764, 2765, 2766, 2767, 2768, 2769, 2770, 2771, 2772, 2773, 2774, 2775, 2776, 2777, 2778, 2779, 2780, 2781, 2782, 2783, 2784, 2785, 2786, 2787, 2788, 2789, 2790, 2791, 2792, 2793, 2794, 2795, 2796, 2797, 2798, 2799, 2800, 2801, 2802, 2803, 2804, 2805, 2806, 2807, 2808, 2809, 2810, 2811, 2812, 2813, 2814, 2815, 2816, 2817, 2818, 2819, 2820, 2821, 2822, 2823, 2824, 2825, 2826, 2827, 2828, 2829, 2830, 2831, 2832, 2833, 2834, 2835, 2836, 2837, 2838, 2839, 2840, 2841, 2842, 2843, 2844, 2845, 2846, 2847, 2848, 2849, 2850, 2851, 2852, 2853, 2854, 2855, 2856, 2857, 2858, 2859, 2860, 2861, 2862, 2863, 2864, 2865, 2866, 2867, 2868, 2869, 2870, 2871, 2872, 2873, 2874, 2875, 2876, 2877, 2878, 2879, 2880, 2881, 2882, 2883, 2884, 2885, 2886, 2887, 2888, 2889, 2890, 2891, 2892, 2893, 2894, 2895, 2896, 2897, 2898, 2899, 2900, 2901, 2902, 2903, 2904, 2905, 2906, 2907, 2908, 2909, 2910, 2911, 2912, 2913, 2914, 2915, 2916, 2917, 2918, 2919, 2920, 2921, 2922, 2923, 2924, 2925, 2926, 2927, 2928, 2929, 2930, 2931, 2932, 2933, 2934, 2935, 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943, 2944, 2945, 2946, 2947, 2948, 2949, 2950, 2951, 2952, 2953, 2954, 2955, 2956, 2957, 2958, 2959, 2960, 2961, 2962, 2963, 2964, 2965, 2966, 2967, 2968, 2969, 2970, 2971, 2972, 2973, 2974, 2975, 2976, 2977, 2978, 2979, 2980, 2981, 2982, 2983, 2984, 2985, 2986, 2987, 2988, 2989, 2990, 2991, 2992, 2993, 2994, 2995, 2996, 2997, 2998, 2999, 3000, 3001, 3002, 3003, 3004, 3005, 3006, 3007, 3008, 3009, 3010, 3011, 3012, 3013, 3014, 3015, 3016, 3017, 3018, 3019, 3020, 3021, 3022, 3023, 3024, 3025, 3026, 3027, 3028, 3029, 3030, 3031, 3032, 3033, 3034, 3035, 3036, 3037, 3038, 3039, 3040, 3041, 3042, 3043, 3044, 3045, 3046, 3047, 3048, 3049, 3050, 3051, 3052, 3053, 3054, 3055, 3056, 3057, 3058, 3059, 3060, 3061, 3062, 3063, 3064, 3065, 3066, 3067, 3068, 3069, 3070, 3071, 3072, 3073, 3074, 3075, 3076, 3077, 3078, 3079, 3080, 3081, 3082, 3083, 3084, 3085, 3086, 3087, 3088, 3089, 3090, 3091, 3092, 3093, 3094, 3095, 3096, 3097, 3098, 3099, 3100, 3101, 3102, 3103, 3104, 3105, 3106, 3107, 3108, 3109, 3110, 3111, 3112, 3113, 3114, 3115, 3116, 3117, 3118, 3119, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127, 3128, 3129, 3130, 3131, 3132, 3133, 3134, 3135, 3136, 3137, 3138, 3139, 3140, 3141, 3142, 3143, 3144, 3145, 3146, 3147, 3148, 3149, 3150, 3151, 3152, 3153, 3154, 3155, 3156, 3157, 3158, 3159, 3160, 3161, 3162, 3163, 3164, 3165, 3166, 3167, 3168, 3169, 3170, 3171, 3172, 3173, 3174, 3175, 3176, 3177, 3178, 3179, 3180, 3181, 3182, 3183, 3184, 3185, 3186, 3187, 3188, 3189, 3190, 3191, 3192, 3193, 3194, 3195, 3196, 3197, 3198, 3199, 3200, 3201, 3202, 3203, 3204, 3205, 3206, 3207, 3208, 3209, 3210, 3211, 3212, 3213, 3214, 3215, 3216, 3217, 3218, 3219, 3220, 3221, 3222, 3223, 3224, 3225, 3226, 3227, 3228, 3229, 3230, 3231, 3232, 3233, 3234, 3235, 3236, 3237, 3238, 3239, 3240, 3241, 3242, 3243, 3244, 3245, 3246, 3247, 3248, 3249, 3250, 3251, 3252, 3253, 3254, 3255, 3256, 3257, 3258, 3259, 3260, 3261, 3262, 3263, 3264, 3265, 3266, 3267, 3268, 3269, 3270, 3271, 3272, 3273, 3274, 3275, 3276, 3277, 3278, 3279, 3280, 3281, 3282, 3283, 3284, 3285, 3286, 3287, 3288, 3289, 3290, 3291, 3292, 3293, 3294, 3295, 3296, 3297, 3298, 3299, 3300, 3301, 3302, 3303, 3304, 3305, 3306, 3307, 3308, 3309, 3310, 3311, 3312, 3313, 3314, 3315, 3316, 3317, 3318, 3319, 3320, 3321, 3322, 3323, 3324, 3325, 3326, 3327, 3328, 3329, 3330, 3331, 3332, 3333, 3334, 3335, 3336, 3337, 3338, 3339, 3340, 3341, 3342, 3343, 3344, 3345, 3346, 3347, 3348, 3349, 3350, 3351, 3352, 3353, 3354, 3355, 3356, 3357, 3358, 3359, 3360, 3361, 3362, 3363, 3364, 3365, 3366, 3367, 3368, 3369, 3370, 3371, 3372, 3373, 3374, 3375, 3376, 3377, 3378, 3379, 3380, 3381, 3382, 3383, 3384, 3385, 3386, 3387, 3388, 3389, 3390, 3391, 3392, 3393, 3394, 3395, 3396, 3397, 3398, 3399, 3400, 3401, 3402, 3403, 3404, 3405, 3406, 3407, 3408, 3409, 3410, 3411, 3412, 3413, 3414, 3415, 3416, 3417, 3418, 3419, 3420, 3421, 3422, 3423, 3424, 3425, 3426, 3427, 3428, 3429, 3430, 3431, 3432, 3433, 3434, 3435, 3436, 3437, 3438, 3439, 3440, 3441, 3442, 3443, 3444, 3445, 3446, 3447, 3448, 3449, 3450, 3451, 3452, 3453, 3454, 3455, 3456, 3457, 3458, 3459, 3460, 3461, 3462, 3463, 3464, 3465, 3466, 3467, 3468, 3469, 3470, 3471, 3472, 3473, 3474, 3475, 3476, 3477, 3478, 3479, 3480, 3481, 3482, 3483, 3484, 3485, 3486, 3487, 3488, 3489, 3490, 3491, 3492, 3493, 3494, 3495, 3496, 3497, 3498, 3499, 3500, 3501, 3502, 3503, 3504, 3505, 3506, 3507, 3508, 3509, 3510, 3511, 3512, 3513, 3514, 3515, 3516, 3517, 3518, 3519, 3520, 3521, 3522, 3523, 3524, 3525, 3526, 3527, 3528, 3529, 3530, 3531, 3532, 3533, 3534, 3535, 3536, 3537, 3538, 3539, 3540, 3541, 3542, 3543, 3544, 3545, 3546, 3547, 3548, 3549, 3550, 3551, 3552, 3553, 3554, 3555, 3556, 3557, 3558, 3559, 3560, 3561, 3562, 3563, 3564, 3565, 3566, 3567, 3568, 3569, 3570, 3571, 3572, 3573, 3574, 3575, 3576, 3577, 3578, 3579, 3580, 3581, 3582, 3583, 3584, 3585, 3586, 3587, 3588, 3589, 3590, 3591, 3592, 3593, 3594, 3595, 3596, 3597, 3598, 3599, 3600, 3601, 3602, 3603, 3604, 3605, 3606, 3607, 3608, 3609, 3610, 3611, 3612, 3613, 3614, 3615, 3616, 3617, 3618, 3619, 3620, 3621, 3622, 3623, 3624, 3625, 3626, 3627, 3628, 3629, 3630, 3631, 3632, 3633, 3634, 3635, 3636, 3637, 3638, 3639, 3640, 3641, 3642, 3643, 3644, 3645, 3646, 3647, 3648, 3649, 3650, 3651, 3652, 3653, 3654, 3655, 3656, 3657, 3658, 3659, 3660, 3661, 3662, 3663, 3664, 3665, 3666, 3667, 3668, 3669, 3670, 3671, 3672, 3673, 3674, 3675, 3676, 3677, 3678, 3679, 3680, 3681, 3682, 3683, 3684, 3685, 3686, 3687, 3688, 3689, 3690, 3691, 3692, 3693, 3694, 3695, 3696, 3697, 3698, 3699, 3700, 3701, 3702, 3703, 3704, 3705, 3706, 3707, 3708, 3709, 3710, 3711, 3712, 3713, 3714, 3715, 3716, 3717, 3718, 3719, 3720, 3721, 3722, 3723, 3724, 3725, 3726, 3727, 3728, 3729, 3730, 3731, 3732, 3733, 3734, 3735, 3736, 3737, 3738, 3739, 3740, 3741, 3742, 3743, 3744, 3745, 3746, 3747, 3748, 3749, 3750, 3751, 3752, 3753, 3754, 3755, 3756, 3757, 3758, 3759, 3760, 3761, 3762, 3763, 3764, 3765, 3766, 3767, 3768, 3769, 3770, 3771, 3772, 3773, 3774, 3775, 3776, 3777, 3778, 3779, 3780, 3781, 3782, 3783, 3784, 3785, 3786, 3787, 3788, 3789, 3790, 3791, 3792, 3793, 3794, 3795, 3796, 3797, 3798, 3799, 3800, 3801, 3802, 3803, 3804, 3805, 3806, 3807, 3808, 3809, 3810, 3811, 3812, 3813, 3814, 3815, 3816, 3817, 3818, 3819, 3820, 3821, 3822, 3823, 3824, 3825, 3826, 3827, 3828, 3829, 3830, 3831, 3832, 3833, 3834, 3835, 3836, 3837, 3838, 3839, 3840, 3841, 3842, 3843, 3844, 3845, 3846, 3847, 3848, 3849, 3850, 3851, 3852, 3853, 3854, 3855, 3856, 3857, 3858, 3859, 3860, 3861, 3862, 3863, 3864, 3865, 3866, 3867, 3868, 3869, 3870, 3871, 3872, 3873, 3874, 3875, 3876, 3877, 3878, 3879, 3880, 3881, 3882, 3883, 3884, 3885, 3886, 3887, 3888, 3889, 3890, 3891, 3892, 3893, 3894, 3895, 3896, 3897, 3898, 3899, 3900, 3901, 3902, 3903, 3904, 3905, 3906, 3907, 3908, 3909, 3910, 3911, 3912, 3913, 3914, 3915, 3916, 3917, 3918, 3919, 3920, 3921, 3922, 3923, 3924, 3925, 3926, 3927, 3928, 3929, 3930, 3931, 3932, 3933, 3934, 3935, 3936, 3937, 3938, 3939, 3940, 3941, 3942, 3943, 3944, 3945, 3946, 3947, 3948, 3949, 3950, 3951, 3952, 3953, 3954, 3955, 3956, 3957, 3958, 3959, 3960, 3961, 3962, 3963, 3964, 3965, 3966, 3967, 3968, 3969, 3970, 3971, 3972, 3973, 3974, 3975, 3976, 3977, 3978, 3979, 3980, 3981, 3982, 3983, 3984, 3985, 3986, 3987, 3988, 3989, 3990, 3991, 3992, 3993, 3994, 3995, 3996, 3997, 3998, 3999, 4000, 4001, 4002, 4003, 4004, 4005, 4006, 4007, 4008, 4009, 4010, 4011, 4012, 4013, 4014, 4015, 4016, 4017, 4018, 4019, 4020, 4021, 4022, 4023, 4024, 4025, 4026, 4027, 4028, 4029, 4030, 4031, 4032, 4033, 4034, 4035, 4036, 4037, 4038, 4039, 4040, 4041, 4042, 4043, 4044, 4045, 4046, 4047, 4048, 4049, 4050, 4051, 4052, 4053, 4054, 4055, 4056, 4057, 4058, 4059, 4060, 4061, 4062, 4063, 4064, 4065, 4066, 4067, 4068, 4069, 4070, 4071, 4072, 4073, 4074, 4075, 4076, 4077, 4078, 4079, 4080, 4081, 4082, 4083, 4084, 4085, 4086, 4087, 4088, 4089, 4090, 4091, 4092, 4093, 4094, 4095, 4096, 4097, 4098, 4099, 4100, 4101, 4102, 4103, 4104, 4105, 4106, 4107, 4108, 4109, 4110, 4111, 4112, 4113, 4114, 4115, 4116, 4117, 4118, 4119, 4120, 4121, 4122, 4123, 4124, 4125, 4126, 4127, 4128, 4129, 4130, 4131, 4132, 4133, 4134, 4135, 4136, 4137, 4138, 4139, 4140, 4141, 4142, 4143, 4144, 4145, 4146, 4147, 4148, 4149, 4150, 4151, 4152, 4153, 4154, 4155, 4156, 4157, 4158, 4159, 4160, 4161, 4162, 4163, 4164, 4165, 4166, 4167, 4168, 4169, 4170, 4171, 4172, 4173, 4174, 4175, 4176, 4177, 4178, 4179, 4180, 4181, 4182, 4183, 4184, 4185, 4186, 4187, 4188, 4189, 4190, 4191, 4192, 4193, 4194, 4195, 4196, 4197, 4198, 4199, 4200, 4201, 4202, 4203, 4204, 4205, 4206, 4207, 4208, 4209, 4210, 4211, 4212, 4213, 4214, 4215, 4216, 4217, 4218, 4219, 4220, 4221, 4222, 4223, 4224, 4225, 4226, 4227, 4228, 4229, 4230, 4231, 4232, 4233, 4234, 4235, 4236, 4237, 4238, 4239, 4240, 4241, 4242, 4243, 4244, 4245, 4246, 4247, 4248, 4249, 4250, 4251, 4252, 4253, 4254, 4255, 4256, 4257, 4258, 4259, 4260, 4261, 4262, 4263, 4264, 4265, 4266, 4267, 4268, 4269, 4270, 4271, 4272, 4273, 4274, 4275, 4276, 4277, 4278, 4279, 4280, 4281, 4282, 4283, 4284, 4285, 4286, 4287, 4288, 4289, 4290, 4291, 4292, 4293, 4294, 4295, 4296, 4297, 4298, 4299, 4300, 4301, 4302, 4303, 4304, 4305, 4306, 4307, 4308, 4309, 4310, 4311, 4312, 4313, 4314, 4315, 4316, 4317, 4318, 4319, 4320, 4321, 4322, 4323, 4324, 4325, 4326, 4327, 4328, 4329, 4330, 4331, 43

In [ ]:
concat_df.loc[concat_df['simulation']<1001]

,vdw_ALA_172_C_VAL_161_O,vdw_GLY_49_CA_MET_76_CE,vdw_GLY_52_O_ILE_149_N,vdw_ILE_114_CA_ILE_163_CD,vdw_GLY_185_C_LEU_189_CD1,vdw_ARG_186_CB_THR_190_CG2,vdw_ILE_181_CB_THR_179_CG2,vdw_GLY_17_C_TYR_14_CA,vdw_ILE_32_CG2_ILE_82_CB,vdw_ARG_186_CB_TRP_6_NE1,...,vdw_ALA_127_C_ARG_186_CG,hbsb_PRO_1_O_SER_4_OG,vdw_ILE_149_O_PRO_180_CB,vdw_GLN_117_CD_GLY_134_O,vdw_LEU_5_CB_PHE_3_CD1,vdw_GLU_162_CD_GLU_164_OE1,vdw_GLY_51_C_PHE_152_C,vdw_ASN_98_CG_PRO_1_O,hbsb_GLN_2_NE2_SER_4_N,simulation
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,996
997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,997
998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,998
999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,999
1000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1000

In [ ]:
concat_df.loc[concat_df['simulation']<1001] = "V1"

<ipython-input-56-5366327c23e9>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'V1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  concat_df.loc[concat_df['simulation']<1001] = "V1"

In [ ]:
concat_df.loc[concat_df['simulation']<1001]

TypeError: '<' not supported between instances of 'str' and 'int'

In [ ]:
concat_df

,vdw_ALA_172_C_VAL_161_O,vdw_GLY_49_CA_MET_76_CE,vdw_GLY_52_O_ILE_149_N,vdw_ILE_114_CA_ILE_163_CD,vdw_GLY_185_C_LEU_189_CD1,vdw_ARG_186_CB_THR_190_CG2,vdw_ILE_181_CB_THR_179_CG2,vdw_GLY_17_C_TYR_14_CA,vdw_ILE_32_CG2_ILE_82_CB,vdw_ARG_186_CB_TRP_6_NE1,...,vdw_ALA_127_C_ARG_186_CG,hbsb_PRO_1_O_SER_4_OG,vdw_ILE_149_O_PRO_180_CB,vdw_GLN_117_CD_GLY_134_O,vdw_LEU_5_CB_PHE_3_CD1,vdw_GLU_162_CD_GLU_164_OE1,vdw_GLY_51_C_PHE_152_C,vdw_ASN_98_CG_PRO_1_O,hbsb_GLN_2_NE2_SER_4_N,simulation
0,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1,...,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1
1,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1,...,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1
2,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1,...,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1
3,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1,...,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1
4,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1,...,V1,V1,V1,V1,V1,V1,V1,V1,V1,V1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5001
497,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5002
498,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5003
499,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5004
500,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5005

In [ ]:
interactions_v1 = pd.read_csv('res_V1.csv')

In [ ]:
interactions_db = [interactions_v1, interactions_v11, interactions_v12, interactions_v7, interactions_v8, interactions_v21]

In [ ]:
concat_df = pd.concat(interactions_db)

In [ ]:
concat_df['simulation'] = ''

In [ ]:
concat_df.iloc[0:1001, concat_df.columns.get_loc('simulation')] = 'V1'

In [ ]:
concat_df.iloc[1001:2002, concat_df.columns.get_loc('simulation')] = 'V11'
concat_df.iloc[2002:3003, concat_df.columns.get_loc('simulation')] = 'V12'
concat_df.iloc[3003:4004, concat_df.columns.get_loc('simulation')] = 'V7'
concat_df.iloc[4004:4505, concat_df.columns.get_loc('simulation')] = 'V8'
concat_df.iloc[4505:5006, concat_df.columns.get_loc('simulation')] = 'V21'
concat_df = concat_df.set_index('simulation', append=False)

In [ ]:
concat

NameError: name 'concat' is not defined

In [ ]:
concat_df

,vdw_ALA_172_C_VAL_161_O,vdw_GLY_49_CA_MET_76_CE,vdw_GLY_52_O_ILE_149_N,vdw_ILE_114_CA_ILE_163_CD,vdw_GLY_185_C_LEU_189_CD1,vdw_ARG_186_CB_THR_190_CG2,vdw_ILE_181_CB_THR_179_CG2,vdw_GLY_17_C_TYR_14_CA,vdw_ILE_32_CG2_ILE_82_CB,vdw_ARG_186_CB_TRP_6_NE1,...,hbsb_ALA_133_N_ASN_182_OD1,vdw_ALA_127_C_ARG_186_CG,hbsb_PRO_1_O_SER_4_OG,vdw_ILE_149_O_PRO_180_CB,vdw_GLN_117_CD_GLY_134_O,vdw_LEU_5_CB_PHE_3_CD1,vdw_GLU_162_CD_GLU_164_OE1,vdw_GLY_51_C_PHE_152_C,vdw_ASN_98_CG_PRO_1_O,hbsb_GLN_2_NE2_SER_4_N
simulation,,,,,,,,,,,,,,,,,,,,,
V1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
V1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
V1,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
V1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
V1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
V21,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
V21,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
V21,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
V21,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
V21,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
concat_df.loc['hbsb_THR_125_OG1_THR_26_N'].groupby('simulation').sum()

KeyError: 'hbsb_THR_125_OG1_THR_26_N'

In [ ]:
concat_df.loc['hbsb_THR_125_OG1_THR_26_N']

KeyError: 'hbsb_THR_125_OG1_THR_26_N'

In [ ]:
concat_df.columns.get_loc('hbsb_THR_125_OG1_THR_26_N')

9133

In [ ]:
concat_df['hbsb_THR_125_OG1_THR_26_N'].groupby('simulation').sum()

simulation
V1       2
V11     21
V12    630
V21    464
V7     893
V8     436
Name: hbsb_THR_125_OG1_THR_26_N, dtype: int64

In [ ]:
interactions_v1 = pd.read_csv('res_V1.csv')

In [ ]:
orig_lengths = [df.shape[0] for df in interactions_db]
concat_lengths = [len(concat_df)]
# or cumulatives
import numpy as np
np.cumsum(orig_lengths)

array([1001, 2002, 3003, 4004, 4505, 5006])

In [ ]:
starts = np.cumsum([0]+orig_lengths[:-1])
for df, s in zip(interactions_db, starts):
    # compare first row of df to concat_df at position s
    assert df.iloc[0].equals(concat_df.iloc[s])
    # compare last row
    assert df.iloc[-1].equals(concat_df.iloc[s + len(df)-1])

In [ ]:
concat_df['_source_idx'].value_counts(sort=False)  # counts per source in order
concat_df.groupby('_source_idx').head(1)           # first row of each block

KeyError: '_source_idx'

In [ ]:
for i, df in enumerate(interactions_db):
    df = df.copy()
    df['_source_idx'] = i
    interactions_db[i] = df

concat_df = pd.concat(interactions_db, ignore_index=True)
# verify
assert concat_df['_source_idx'].tolist() == sum([[i]*len(df) for i,df in enumerate(interactions_db)], [])

In [ ]:
co

NameError: name 'co' is not defined

In [ ]:
concat_df

,vdw_ALA_172_C_VAL_161_O,vdw_GLY_49_CA_MET_76_CE,vdw_GLY_52_O_ILE_149_N,vdw_ILE_114_CA_ILE_163_CD,vdw_GLY_185_C_LEU_189_CD1,vdw_ARG_186_CB_THR_190_CG2,vdw_ILE_181_CB_THR_179_CG2,vdw_GLY_17_C_TYR_14_CA,vdw_ILE_32_CG2_ILE_82_CB,vdw_ARG_186_CB_TRP_6_NE1,...,vdw_ALA_127_C_ARG_186_CG,hbsb_PRO_1_O_SER_4_OG,vdw_ILE_149_O_PRO_180_CB,vdw_GLN_117_CD_GLY_134_O,vdw_LEU_5_CB_PHE_3_CD1,vdw_GLU_162_CD_GLU_164_OE1,vdw_GLY_51_C_PHE_152_C,vdw_ASN_98_CG_PRO_1_O,hbsb_GLN_2_NE2_SER_4_N,_source_idx
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
5002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
5003,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
5004,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
5005,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5

In [ ]:
# lengths in order: v1..v21
lengths = [1001, 1001, 1001, 1001, 501, 501]
labels  = ['V1', 'V11', 'V12', 'V7', 'V8', 'V21']

# create a simulation column of same length
concat_df['simulation'] = ''

start = 0
for L, lab in zip(lengths, labels):
    end = start + L
    concat_df.iloc[start:end, concat_df.columns.get_loc('simulation')] = lab
    start = end

# optional: make it the index
concat_df = concat_df.set_index('simulation', append=False)   # or append=True to keep original integer index

In [ ]:
concat_df

,vdw_ALA_172_C_VAL_161_O,vdw_GLY_49_CA_MET_76_CE,vdw_GLY_52_O_ILE_149_N,vdw_ILE_114_CA_ILE_163_CD,vdw_GLY_185_C_LEU_189_CD1,vdw_ARG_186_CB_THR_190_CG2,vdw_ILE_181_CB_THR_179_CG2,vdw_GLY_17_C_TYR_14_CA,vdw_ILE_32_CG2_ILE_82_CB,vdw_ARG_186_CB_TRP_6_NE1,...,vdw_ALA_127_C_ARG_186_CG,hbsb_PRO_1_O_SER_4_OG,vdw_ILE_149_O_PRO_180_CB,vdw_GLN_117_CD_GLY_134_O,vdw_LEU_5_CB_PHE_3_CD1,vdw_GLU_162_CD_GLU_164_OE1,vdw_GLY_51_C_PHE_152_C,vdw_ASN_98_CG_PRO_1_O,hbsb_GLN_2_NE2_SER_4_N,_source_idx
simulation,,,,,,,,,,,,,,,,,,,,,
V1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
V1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
V1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
V1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
V1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
V21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
V21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
V21,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
V21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
V21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5

In [ ]:
concat_df['hbsb_THR_125_OG1_THR_26_N'].groupby('simulation').sum()

simulation
V1       2
V11     21
V12    630
V21    464
V7     893
V8     436
Name: hbsb_THR_125_OG1_THR_26_N, dtype: int64

In [ ]:
concat_df['simulation'].groupby('simulation').sum()

KeyError: 'simulation'

In [ ]:
concat_df['simulation'].groupby('simulation').len()

KeyError: 'simulation'

In [ ]:
concat_df.groupby('simulation').sum()

,vdw_ALA_172_C_VAL_161_O,vdw_GLY_49_CA_MET_76_CE,vdw_GLY_52_O_ILE_149_N,vdw_ILE_114_CA_ILE_163_CD,vdw_GLY_185_C_LEU_189_CD1,vdw_ARG_186_CB_THR_190_CG2,vdw_ILE_181_CB_THR_179_CG2,vdw_GLY_17_C_TYR_14_CA,vdw_ILE_32_CG2_ILE_82_CB,vdw_ARG_186_CB_TRP_6_NE1,...,vdw_ALA_127_C_ARG_186_CG,hbsb_PRO_1_O_SER_4_OG,vdw_ILE_149_O_PRO_180_CB,vdw_GLN_117_CD_GLY_134_O,vdw_LEU_5_CB_PHE_3_CD1,vdw_GLU_162_CD_GLU_164_OE1,vdw_GLY_51_C_PHE_152_C,vdw_ASN_98_CG_PRO_1_O,hbsb_GLN_2_NE2_SER_4_N,_source_idx
simulation,,,,,,,,,,,,,,,,,,,,,
V1,3,0,0,0,264,2,0,0,1,0,...,2,0,0,1,0,0,0,0,0,0
V11,4,0,0,0,140,1,1,0,0,3,...,0,0,4,3,1,2,0,0,2,1001
V12,5,0,0,2,186,0,0,0,0,0,...,10,0,0,3,0,0,1,0,1,2002
V21,8,0,0,0,100,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,2505
V7,4,0,1,0,171,0,0,0,1,0,...,0,0,0,2,0,0,1,0,0,3003
V8,4,0,0,1,56,0,2,1,0,0,...,1,0,0,0,0,0,0,1,0,2004

In [ ]:
len(concat_df['simulation'])

KeyError: 'simulation'

In [ ]:
concat_df['simulation']

KeyError: 'simulation'

In [ ]:
concat_df.index

Index(['V1', 'V1', 'V1', 'V1', 'V1', 'V1', 'V1', 'V1', 'V1', 'V1',
       ...
       'V21', 'V21', 'V21', 'V21', 'V21', 'V21', 'V21', 'V21', 'V21', 'V21'],
      dtype='object', name='simulation', length=5006)

In [ ]:
[len(concat_df)]

[5006]

In [ ]:
[len(concat_df.gr)]

AttributeError: 'DataFrame' object has no attribute 'gr'

In [ ]:
[len(concat_df.groupby('simulation'))]

[6]

In [ ]:
[len(concat_df).groupby('simulation')]

AttributeError: 'int' object has no attribute 'groupby'

In [ ]:
[len(concat_df.index.groupby('simulation'))]

TypeError: Categorical input must be list-like

In [ ]:
[len(concat_df.index)]

[5006]

In [ ]:
len(concat_df.index)

5006

In [ ]:
for sim in concat_df.groupby('simulation'): print(len(sim))

2
2
2
2
2
2

In [ ]:
for sim in concat_df.groupby('simulation'): print(sim)

('V1',             vdw_ALA_172_C_VAL_161_O  vdw_GLY_49_CA_MET_76_CE  \
simulation
V1                                0                        0
V1                                0                        0
V1                                0                        0
V1                                0                        0
V1                                0                        0
...                             ...                      ...
V1                                0                        0
V1                                0                        0
V1                                0                        0
V1                                0                        0
V1                                0                        0

            vdw_GLY_52_O_ILE_149_N  vdw_ILE_114_CA_ILE_163_CD  \
simulation
V1                               0                          0
V1                               0                          0
V1                               0                          0
V1                               0                          0
V1                               0                          0
...                            ...                        ...
V1                               0                          0
V1                               0                          0
V1                               0                          0
V1                               0                          0
V1                               0                          0

            vdw_GLY_185_C_LEU_189_CD1  vdw_ARG_186_CB_THR_190_CG2  \
simulation
V1                                  0                           0
V1                                  0                           0
V1                                  1                           0
V1                                  0                           0
V1                                  0                           0
...                               ...                         ...
V1                                  0                           0
V1                                  0                           0
V1                                  0                           0
V1                                  0                           0
V1                                  0                           0

            vdw_ILE_181_CB_THR_179_CG2  vdw_GLY_17_C_TYR_14_CA  \
simulation
V1                                   0                       0
V1                                   0                       0
V1                                   0                       0
V1                                   0                       0
V1                                   0                       0
...                                ...                     ...
V1                                   0                       0
V1                                   0                       0
V1                                   0                       0
V1                                   0                       0
V1                                   0                       0

            vdw_ILE_32_CG2_ILE_82_CB  vdw_ARG_186_CB_TRP_6_NE1  ...  \
simulation                                                      ...
V1                                 0                         0  ...
V1                                 0                         0  ...
V1                                 0                         0  ...
V1                                 0                         0  ...
V1                                 0                         0  ...
...                              ...                       ...  ...
V1                                 0                         0  ...
V1                                 0                         0  ...
V1                                 0                         0  ...
V1                                 0                         0  ...
V1                                 0                         0  ...

            vdw_ALA_127_C_ARG_186_CG  hbsb_PRO_1_O_SER_4_OG  \
simulation
V1                                 0                      0
V1                                 0                      0
V1                                 0                      0
V1                                 0                      0
V1                                 0                      0
...                              ...                    ...
V1                                 0                      0
V1                                 0                      0
V1                                 0                      0
V1                                 0                      0
V1                                 0                      0

            vdw_ILE_149_O_PRO_180_CB  vdw_GLN_117_CD_GLY_134_O  \
simulation
V1                                 0                         0
V1                                 0                         0
V1                                 0                         0
V1                                 0                         0
V1                                 0                         0
...                              ...                       ...
V1                                 0                         0
V1                                 0                         0
V1                                 0                         0
V1                                 0                         0
V1                                 0                         0

            vdw_LEU_5_CB_PHE_3_CD1  vdw_GLU_162_CD_GLU_164_OE1  \
simulation
V1                               0                           0
V1                               0                           0
V1                               0                           0
V1                               0                           0
V1                               0                           0
...                            ...                         ...
V1                               0                           0
V1                               0                           0
V1                               0                           0
V1                               0                           0
V1                               0                           0

            vdw_GLY_51_C_PHE_152_C  vdw_ASN_98_CG_PRO_1_O  \
simulation
V1                               0                      0
V1                               0                      0
V1                               0                      0
V1                               0                      0
V1                               0                      0
...                            ...                    ...
V1                               0                      0
V1                               0                      0
V1                               0                      0
V1                               0                      0
V1                               0                      0

            hbsb_GLN_2_NE2_SER_4_N  _source_idx
simulation
V1                               0            0
V1                               0            0
V1                               0            0
V1                               0            0
V1                               0            0
...                            ...          ...
V1                               0            0
V1                               0            0
V1                               0            0
V1                               0            0
V1                               0            0

[1001 rows x 21392 columns])
('V11',             vdw_ALA_172_C_VAL_161_O  vdw_GLY_49_CA_MET_76_CE  \
simulation
V11                               0                        0
V11                               0                        0
V11                               0                        0
V11                               0                        0
V11                               0                        0
...                             ...                      ...
V11                               0                        0
V11                               0                        0
V11                               0                        0
V11                               0                        0
V11                               0                        0

            vdw_GLY_52_O_ILE_149_N  vdw_ILE_114_CA_ILE_163_CD  \
simulation
V11                              0                          0
V11                              0                          0
V11                              0                          0
V11                              0                          0
V11                              0                          0
...                            ...                        ...
V11                              0                          0
V11                              0                          0
V11                              0                          0
V11                              0                          0
V11                              0                          0

            vdw_GLY_185_C_LEU_189_CD1  vdw_ARG_186_CB_THR_190_CG2  \
simulation
V11                                 0                           0
V11                                 0                           0
V11                                 0                           0
V11                                 0                           0
V11                                 0                           0
...                               ...                         ...
V11                                 0                           0
V11                                 0                           0
V11                                 0                           0
V11                                 0                           0
V11                                 1                           0

            vdw_ILE_181_CB_THR_179_CG2  vdw_GLY_17_C_TYR_14_CA  \
simulation
V11                                  0                       0
V11                                  0                       0
V11                                  0                       0
V11                                  0                       0
V11                                  0                       0
...                                ...                     ...
V11                                  0                       0
V11                                  0                       0
V11                                  0                       0
V11                                  0                       0
V11                                  0                       0

            vdw_ILE_32_CG2_ILE_82_CB  vdw_ARG_186_CB_TRP_6_NE1  ...  \
simulation                                                      ...
V11                                0                         0  ...
V11                                0                         0  ...
V11                                0                         0  ...
V11                                0                         0  ...
V11                                0                         0  ...
...                              ...                       ...  ...
V11                                0                         0  ...
V11                                0                         0  ...
V11                                0                         0  ...
V11                                0                         0  ...
V11                                0                         0  ...

            vdw_ALA_127_C_ARG_186_CG  hbsb_PRO_1_O_SER_4_OG  \
simulation
V11                                0                      0
V11                                0                      0
V11                                0                      0
V11                                0                      0
V11                                0                      0
...                              ...                    ...
V11                                0                      0
V11                                0                      0
V11                                0                      0
V11                                0                      0
V11                                0                      0

            vdw_ILE_149_O_PRO_180_CB  vdw_GLN_117_CD_GLY_134_O  \
simulation
V11                                0                         0
V11                                0                         0
V11                                0                         0
V11                                0                         0
V11                                0                         0
...                              ...                       ...
V11                                0                         0
V11                                0                         0
V11                                0                         0
V11                                0                         0
V11                                0                         0

            vdw_LEU_5_CB_PHE_3_CD1  vdw_GLU_162_CD_GLU_164_OE1  \
simulation
V11                              0                           0
V11                              0                           0
V11                              0                           0
V11                              0                           0
V11                              0                           0
...                            ...                         ...
V11                              0                           0
V11                              0                           0
V11                              0                           0
V11                              0                           0
V11                              0                           0

            vdw_GLY_51_C_PHE_152_C  vdw_ASN_98_CG_PRO_1_O  \
simulation
V11                              0                      0
V11                              0                      0
V11                              0                      0
V11                              0                      0
V11                              0                      0
...                            ...                    ...
V11                              0                      0
V11                              0                      0
V11                              0                      0
V11                              0                      0
V11                              0                      0

            hbsb_GLN_2_NE2_SER_4_N  _source_idx
simulation
V11                              0            1
V11                              0            1
V11                              0            1
V11                              0            1
V11                              0            1
...                            ...          ...
V11                              0            1
V11                              0            1
V11                              0            1
V11                              0            1
V11                              0            1

[1001 rows x 21392 columns])
('V12',             vdw_ALA_172_C_VAL_161_O  vdw_GLY_49_CA_MET_76_CE  \
simulation
V12                               0                        0
V12                               0                        0
V12                               0                        0
V12                               0                        0
V12                               0                        0
...                             ...                      ...
V12                               0                        0
V12                               0                        0
V12                               0                        0
V12                               0                        0
V12                               0                        0

            vdw_GLY_52_O_ILE_149_N  vdw_ILE_114_CA_ILE_163_CD  \
simulation
V12                              0                          0
V12                              0                          0
V12                              0                          0
V12                              0                          0
V12                              0                          0
...                            ...                        ...
V12                              0                          0
V12                              0                          0
V12                              0                          0
V12                              0                          0
V12                              0                          0

            vdw_GLY_185_C_LEU_189_CD1  vdw_ARG_186_CB_THR_190_CG2  \
simulation
V12                                 0                           0
V12                                 0                           0
V12                                 0                           0
V12                                 0                           0
V12                                 0                           0
...                               ...                         ...
V12                                 0                           0
V12                                 0                           0
V12                                 0                           0
V12                                 0                           0
V12                                 0                           0

            vdw_ILE_181_CB_THR_179_CG2  vdw_GLY_17_C_TYR_14_CA  \
simulation
V12                                  0                       0
V12                                  0                       0
V12                                  0                       0
V12                                  0                       0
V12                                  0                       0
...                                ...                     ...
V12                                  0                       0
V12                                  0                       0
V12                                  0                       0
V12                                  0                       0
V12                                  0                       0

            vdw_ILE_32_CG2_ILE_82_CB  vdw_ARG_186_CB_TRP_6_NE1  ...  \
simulation                                                      ...
V12                                0                         0  ...
V12                                0                         0  ...
V12                                0                         0  ...
V12                                0                         0  ...
V12                                0                         0  ...
...                              ...                       ...  ...
V12                                0                         0  ...
V12                                0                         0  ...
V12                                0                         0  ...
V12                                0                         0  ...
V12                                0                         0  ...

            vdw_ALA_127_C_ARG_186_CG  hbsb_PRO_1_O_SER_4_OG  \
simulation
V12                                0                      0
V12                                1                      0
V12                                0                      0
V12                                0                      0
V12                                0                      0
...                              ...                    ...
V12                                0                      0
V12                                0                      0
V12                                0                      0
V12                                0                      0
V12                                0                      0

            vdw_ILE_149_O_PRO_180_CB  vdw_GLN_117_CD_GLY_134_O  \
simulation

In [ ]:
for sim in concat_df.groupby('simulation'): print(pd.DataFrame(sim).shape)

(2, 1)
(2, 1)
(2, 1)
(2, 1)
(2, 1)
(2, 1)

In [ ]:
for sim in concat_df.groupby('simulation'): print(sim.shape)

AttributeError: 'tuple' object has no attribute 'shape'

In [ ]:
for sim in concat_df.groupby('simulation'): print(len(sim[1]))

1001
1001
1001
501
1001
501

In [ ]:
concat_df['hbsb_THR_125_O_THR_26_OG1'].groupby('simulation').sum()

simulation
V1     680
V11     24
V12      0
V21      0
V7       0
V8       0
Name: hbsb_THR_125_O_THR_26_OG1, dtype: int64